export const ADD_ALL_IMAGES = 'ADD_ALL_IMAGES';
export const ADD_IMAGES_FAILURE = 'ADD_IMAGES_FAILURE';
export const ADD_IMAGES_STARTED = 'ADD_IMAGES_STARTED';
export const SET_CURRENT_ID_IMAGE = 'SET_CURRENT_ID_IMAGE';
export const SET_HAMBURGER_OPEN = 'SET_HAMBURGER_OPEN';
export const ADD_IMAGES_FINISHED = 'ADD_IMAGES_FINISHED';


